// demos/next/app/page.tsx
export default function HomePage() {
    return (
        <main style={{ padding: '2rem', lineHeight: 1.5 }}>
            <h1>Dokie Next Demo</h1>
            <p>This demo uses Dokie at the Next.js route-handler level via standard Request/Response APIs.</p>
            <ul>
                <li>
                    <a href="/dokie">Open Dokie UI</a>
                </li>
                <li>
                    <a href="/api/openapi.json">Open OpenAPI JSON</a>
                </li>
                <li>
                    <a href="/api/hello">Open sample API route</a>
                </li>
            </ul>
        </main>
    );
}

// demos/nuxt/app.vue
<template>
    <main style="padding: 2rem; font-family: sans-serif; line-height: 1.5">
        <h1>Dokie Nuxt Demo</h1>
        <p>This demo uses Dokie from a Nitro server route. It is not a dedicated Nuxt adapter.</p>
        <ul>
            <li><a href="/dokie">Open Dokie UI</a></li>
            <li><a href="/openapi.json">Open OpenAPI JSON</a></li>
            <li><a href="/hello">Open sample API route</a></li>
        </ul>
    </main>
</template>
